### ISSUE TITLE
3RScan Dataset Preprocess

### ISSUE THREAD

**Issue by Yioutpi** [embodied-generalist/embodied-generalist#21]
Thanks for your interesting work.
3RScan-ours-align folder include three .pth files, is there some difference between pcd-align.pth and pcds two files? Could you provide tools for converting the raw 3RScan data to your format?

**Comment by huangjy-pku** [comment]
We use the `pcd-align.pth` files for scene point clouds, which are processed more properly. We generate the `pcd-align` point cloud files with the following procedures:
1) sample points from the raw mesh file
2) use the ground-truth segmentation to obtain per-point label
3) rotate the point clouds so that most object bounding boxes are axis-aligned, following ScanRefer
4) translate the point clouds so that the origin is at the center on the floor
5) subsample the point clouds if the number of points exceeds 240k.

Overall, the data preprocess shares a similar strategy to [SceneVerse](https://scene-verse.github.io/), wherein more details can be found in the supplementary.

**Comment by Yioutpi** [comment]
Thanks for your reply!

For step 3 and 4, but how do you get the axis-aligned and translation matrix such as ScanNet?

**Comment by huangjy-pku** [comment]
We search for a rotation matrix that makes most bounding boxes axis-aligned.

**Comment by Yioutpi** [comment]
When processing 3RScans data as you mentioned, we are still a bit confused. ScanRefer uses the axis-aligned parameter for rotation and translation, but 3RScan does not. Can you provide the code for handling 3RScan data? Specifically, for step 3 and 4. Thanks!

**Comment by huangjy-pku** [comment]
We will wrap up the code and inform you after it is done.

**Comment by huangjy-pku** [comment]
Sorry for being late. Check details [here](https://github.com/scene-verse/SceneVerse/blob/main/preprocess/README.md).
